In [3]:
import pandas as pd
import numpy as np

ihs = pd.read_excel(r"C:/Users/40107922/OneDrive - Anheuser-Busch InBev/hackathon_2025/repo/hackathon_2025/optimization_data/IHS.xlsx")
sellout_train = pd.read_excel(r"C:/Users/40107922/OneDrive - Anheuser-Busch InBev/hackathon_2025/repo/hackathon_2025/optimization_data/Sellout_Train.xlsx")
sellout_test = pd.read_excel(r"C:/Users/40107922/OneDrive - Anheuser-Busch InBev/hackathon_2025/repo/hackathon_2025/optimization_data/Sellout_Test.xlsx")
price_list = pd.read_excel(r"C:/Users/40107922/OneDrive - Anheuser-Busch InBev/hackathon_2025/repo/hackathon_2025/optimization_data/Price_List.xlsx")
sellin = pd.read_excel(r"C:/Users/40107922/OneDrive - Anheuser-Busch InBev/hackathon_2025/repo/hackathon_2025/optimization_data/Sellin.xlsx")

data_list = [ihs, sellout_train, sellout_test, price_list, sellin]
for df in data_list:
    df.columns = [col.lower() for col in df.columns]

In [29]:
sellin.loc[3]

scenario                     2019
country                  Colombia
region                        All
channel                       All
month_number                    1
skuid                        2170
brand                Aguila Light
pack                          CAN
size                          330
volume               17948.632812
gto             8740405436.286659
discount            -972765692.27
excise          -2323811417.04666
nr                  5443828326.97
vic             -2299651251.84538
vlc             -359825817.180455
macostd          2784351257.94417
maco            3757116950.214164
maco_check       972765692.269994
Name: 3, dtype: object

In [30]:
sellin['maco'] = sellin['gto'] + (sellin['vic']+sellin['vlc']) + sellin['excise'] + sellin['discount']
sellin['maco_check'] = sellin['maco'] - sellin['macostd']
sellin

,scenario,country,region,channel,month_number,skuid,brand,pack,size,volume,gto,discount,excise,nr,vic,vlc,macostd,maco,maco_check
0,2019,Colombia,All,All,1,1413,Costeña,CAN,330,-0.050000,-2.030610e+04,0.000000e+00,4.724160e+03,-1.558194e+04,6.404440e+03,2.199034e+01,-9.155510e+03,-9.155510e+03,-7.275958e-12
1,2019,Colombia,All,All,1,3154,Poker,CAN,330,-0.040000,-1.790539e+04,0.000000e+00,3.376072e+03,-1.452932e+04,5.120886e+03,1.624168e+01,-9.392190e+03,-9.392190e+03,3.637979e-12
2,2019,Colombia,All,All,1,8216,Poker,CAN,355,-0.010000,-3.253307e+03,0.000000e+00,9.223172e+02,-2.330990e+03,8.815115e+02,-1.120789e-01,-1.449591e+03,-1.449591e+03,-2.046363e-12
3,2019,Colombia,All,All,1,2170,Aguila Light,CAN,330,17948.632812,8.740405e+09,-9.727657e+08,-2.323811e+09,5.443828e+09,-2.299651e+09,-3.598258e+08,2.784351e+09,2.784351e+09,-5.722046e-06
4,2019,Colombia,All,All,1,5905,Aguila Light,CAN,473,2070.219971,8.162681e+08,-4.110808e+07,-1.881640e+08,5.869960e+08,-2.384227e+08,-8.592555e+07,2.626478e+08,2.626478e+08,-7.152557e-07
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19551,2023,Colombia,All,All,9,17289,Corona Tropical,CAN,355,-0.060000,-3.131400e+04,0.000000e+00,0.000000e+00,-3.131400e+04,2.747347e+04,1.532695e+04,1.148642e+04,1.148642e+04,0.000000e+00
19552,2023,Colombia,All,All,9,18217,Corona Tropical,CAN,355,-1.470000,-5.745600e+05,0.000000e+00,0.000000e+00,-5.745600e+05,7.139338e+05,3.821785e+05,5.215523e+05,5.215523e+05,0.000000e+00
19553,2023,Colombia,All,All,9,2182,Pony Malta,RB,330,35516.910000,1.349841e+10,-1.284276e+09,0.000000e+00,1.221414e+10,-2.641024e+09,-1.069844e+09,8.503268e+09,8.503268e+09,-9.536743e-07
19554,2023,Colombia,All,All,9,Tada - Retail,Tada Retail,Other,Other,9203.000000,7.638845e+09,-1.446374e+09,-9.856957e+07,6.093902e+09,-5.695273e+09,-4.281160e+08,-2.948699e+07,-2.948699e+07,-1.974404e-07
19555,2023,Colombia,All,All,9,20012,Corona Tropical,CAN,355,61.860000,1.040683e+08,-2.119176e+07,-2.944318e+07,5.343340e+07,-3.456058e+07,-1.805306e+07,8.197657e+05,8.197657e+05,-1.478475e-08

In [38]:
# (2000 - 1641.667)/1641.667
price_list

,date,category,sku,capacity_ml,no_units,no_units_liters,cod_material,ptr,ptc,mark_up
0,2024-02-22,Core,"Aguila 0,0 NRB 330",330,24.0,24,null,1641.666667,2000.0,0.218274
1,2023-11-02,Core,"Aguila 0,0 NRB 330",330,24.0,24,null,1641.666667,2000.0,0.218274
2,2023-11-22,Core,"Aguila 0,0 NRB 330",330,24.0,24,null,1641.666667,2000.0,0.218274
3,2024-02-02,Core,"Aguila 0,0 NRB 330",330,24.0,24,null,1641.666667,2000.0,0.218274
4,2023-07-06,Core,"Aguila 0,0 NRB 330",330,24.0,24,null,1641.666667,2000.0,0.218274
...,...,...,...,...,...,...,...,...,...,...
10910,2023-08-01,Zalva SS,Zalva PET 600,600,24.0,24,null,1250.000000,1500.0,0.200000
10911,2023-06-16,Zalva SS,Zalva PET 600,600,24.0,24,null,1250.000000,1500.0,0.200000
10912,2023-07-21,Zalva SS,Zalva PET 600,600,24.0,24,null,1250.000000,1500.0,0.200000
10913,2024-02-22,Zalva SS,Zalva PET 600,600,24.0,24,null,1416.666667,1700.0,0.200000
10914,2024-01-01,Zalva SS,Zalva PET 600,600,24.0,24,null,1416.666667,1700.0,0.200000

In [ ]:
sellin[19553].sum()

scenario                      2023
country                   Colombia
region                         All
channel                        All
month_number                     9
skuid                         2182
brand                   Pony Malta
pack                            RB
size                           330
volume                    35516.91
gto                 13498411560.99
discount            -1284275848.62
excise                         0.0
nr              12214135712.370001
vic               -2641023931.1742
vlc              -1069843517.51126
macostd           8503268263.68454
maco             8503268263.684539
maco_check               -0.000001
Name: 19553, dtype: object

In [26]:
-20306.1 + (6404.43995 +  21.990343) + 4724.16

-9155.509706999997

In [23]:
-0.05 - (6404.43995 +  21.990343) #- 4724.16

-6426.4802930000005

In [18]:
print("Sellout Train columns:", sellout_train.columns.tolist())
print("\nPrice List columns:", price_list.columns.tolist())
print("\nSellout Train shape:", sellout_train.shape)
print("\nPrice List shape:", price_list.shape)

Sellout Train columns: ['date', 'market', 'manufacturer', 'brand', 'sub_brand', 'package', 'package_type', 'capacity_number', 'sales_value', 'sales_hectoliters', 'numeric_distribution_stores_handling', 'avg_price_per_liter', 'inventory_hectoliters', 'weighted_distribution_tdp_reach']

Price List columns: ['date', 'category', 'sku', 'capacity_ml', 'no_units', 'no_units_liters', 'cod_material', 'ptr', 'ptc', 'mark_up']

Sellout Train shape: (12982, 14)

Price List shape: (10915, 10)